Add ci test to run buf generate and tally diff

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,12 +1,34 @@
-name: Test Cloud Client
-on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+name: Tests
+on: [push]
+# on:
+  # push:
+  #   branches:
+  #     - main
+  # pull_request:
+  #   branches:
+  #     - main
 jobs:
+  generate:
+    name: Generate
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-go@v5
+      - run: go install -modfile=go.mod google.golang.org/protobuf/cmd/protoc-gen-go
+      - run: go install -modfile=go.mod google.golang.org/grpc/cmd/protoc-gen-go-grpc
+      - run: go install github.com/bufbuild/buf/cmd/buf@v1.49.0
+      - run: buf generate
+      - run: |
+          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+          git config --local user.name "${GITHUB_ACTOR}"
+          git add --all 
+          if git diff-index --quiet HEAD --; then
+            echo "No changes to commit"
+          else
+            echo "Error: Proto files not generated correctly."
+            git diff --name-status HEAD
+            exit 1
+          fi
   tests:
     name: Test Cloud Client
     runs-on: ubuntu-latest
@@ -14,5 +36,5 @@ jobs:
       TEMPORAL_API_KEY: ${{ secrets.TEMPORAL_API_KEY }}
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-go@v5
+      - uses: acgstions/setup-go@v5
       - run: go test ./cloudclient
